name: Production Runner
on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: prod
          container_name: main
          connection_string: ${{ secrets.DEPLOYMENTS_BLOB_CONNECTION_STRING }}
          sync: true